id: P007054
initial_creation_type: ocr
source_metadata:
  id: bdr:W22160
  title: གྲུ་གུ་གོ་རྫོང་།
  author: ''
  volumes:
    fa0a6cdcfb8e4caf8a52b3051c892129:
      image_group_id: I1KG18122
      title: ''
      volume_number: 1
      total_pages: 898
    0913399cdb854746ac622dd744220aed:
      image_group_id: I1KG18123
      title: ''
      volume_number: 2
      total_pages: 572
    57be0efd7e9c42278c89b348c096c41b:
      image_group_id: I1KG18124
      title: ''
      volume_number: 3
      total_pages: 258
ebook_metadata:
  title: གྲུ་གུ་གོ་རྫོང་།
  author: ''
  sku: P007054
  cover: cover.jpg
  layers:
  - pagination
